### ISSUE TITLE
Setup: Make Worker and Stasd docker container optional in dev environment.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#4497]
## Issue:

Currently when we run `docker-compose up`, all the containers are spinned up which we don't even need for development. So, make worker and statsd containers as optional.

Here is the code to do it:

```
version: "3.9"
services:
  db:
    image: postgres:10.4
    ports:
      - "5432:5432"

  sqs:
    image: softwaremill/elasticmq
    hostname: sqs
    ports:
      - 9324:9324

  django:
    hostname: django
    env_file:
      - docker/dev/docker.env
    build:
      context: ./
      dockerfile: docker/dev/django/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - sqs
      - statsd-exporter
    volumes:
      - .:/code

  worker:
    env_file:
      - docker/dev/docker.env
    image: my_custom_worker_image  # Default image used if not built
    build:
      context: ./
      dockerfile: docker/dev/worker/Dockerfile
      x-enabled: ${BUILD_WORKER:-false}  # Only build if BUILD_WORKER=true
    depends_on:
      - django
    volumes:
      - .:/code
    profiles:
      - worker  # Only built when this profile is specified

  worker_py3_8:
    env_file:
      - docker/dev/docker.env
    image: my_custom_worker_py3_8_image  # Default image used if not built
    build:
      context: ./
      dockerfile: docker/dev/worker_py3.8/Dockerfile
      x-enabled: ${BUILD_WORKER:-false}
    depends_on:
      - django
    volumes:
      - .:/code
    profiles:
      - worker

  nodejs:
    hostname: nodejs
    build:
      context: ./
      dockerfile: docker/dev/nodejs/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "8888:8888"
      - "35729:35729"
    volumes:
      - .:/code
      - /code/node_modules
      - /code/bower_components

  statsd-exporter:
    hostname: statsd
    image: prom/statsd-exporter:latest
    build:
      context: ./
      dockerfile: docker/dev/statsd-exporter/Dockerfile
      x-enabled: ${BUILD_STATSD:-false}  # Only build if BUILD_STATSD=true
    command:
      - '--log.level=info'
      - '--web.telemetry-path=/statsd/metrics'
    ports:
      - '9125:9125'
      - '9102:9102'
    profiles:
      - statsd  # Only built when this profile is specified
```

## Deliverables:

- [ ] Use the code to check if it works correctly. If not, fix it.
- [ ] Add documentation for it in the readme for running the containers.
